# 22/04/23 <

print("Hello Python3")
name_hello = "Hello Python Remote EE 19"
print(name_hello)
number1, string1, boolean1 = 8, "hey", True
print(number1, string1, boolean1, sep="\n")

# 23/04/23 <

# string, str
print("Hello World!")

# integer, int
print(12)

# float
print(12.12)

# Boolean, bool
print(True)
print(None)

# Variables

name = "Alexandre"
number = 30
number2 = 15
some_text = "Lorem Ipsum auto generated by my fingers :)"
a_number_with_dot = 1.1
logical_value = True

print(number)
number = 45
print(number)

# Arithmetic operators

print(1+1)
print(7-2)
print(2*2)
print(2**4)
print(9/3)
print(9//3)
print(9 % 3)

# Comparison operators

print(1==2)
print(1!=2)
print(1<=2)
print(1>=2)
print(1<2)
print(1>2)

# Assignment operators

simple = "simple"
number += 10
print(number)
number -= 3
print(number)
number *= 7
print(number)
number **= 7
print(number)
number /= 500
print(number)
print("simple")

# Identify operators

print(number is number)
print(number is not number2)

# Logical operators

print(number is number2 and number is not a_number_with_dot)
print(number is number2 or number is not number2)

# Membership operators

print("i" in some_text)
print("x" not in some_text)
print("z" in some_text)

# Combining variables

print(name,"",some_text)
print((name+ " ")*5)
print(f"{name} is so great and {some_text}")

# Input()

print("Hello Stanger, what is your name ? ")
name = input()
print(f"I'm glad to meet you {name} !")

age = input("What is your age " + name + " ? \n")
